### ISSUE TITLE
`hot.addDisposeHandler is not a function` error when using Parcel

### ISSUE THREAD

**Issue by steadicat** [smyte/jsxstyle#100]
I just added `jsxstyle` to a new project (using TypeScript and Parcel), and nothing seems to work. I get the following error:

![screen shot 2018-02-01 at 11 04 15 am](https://user-images.githubusercontent.com/6031/35697649-aa934a1a-073f-11e8-9f73-0ea14fb5308f.png)

**Comment by meyer** [comment]
@steadicat ah yep, looks like Parcel uses a slightly different implementation of webpack’s HMR API (https://github.com/parcel-bundler/parcel/issues/619). Should be easy to fix.

**Comment by meyer** [comment]
Fixed, publishing a new version in a sec.

**Comment by meyer** [comment]
Published as `jsxstyle@2.0.10`. Thanks @steadicat!
