### ISSUE TITLE
Switch from React.CSSProperties to csstype

### ISSUE THREAD

**Issue by meyer** [smyte/jsxstyle#104]
@frenic has done a nice job of automating conversion of MDN CSS data to TypeScript (and Flow!) types. Moving to [csstype](https://github.com/frenic/csstype) would remove the dependency on `@types/react` for Preact folks and we'd hopefully be able to remove the string index accessor as well. Benefits all around.

**Comment by meyer** [comment]
implemented in 273c1924dfc0e7b416f22ae79dade63346817a6a

**Comment by jaredpalmer** [comment]
Nice!
