### ISSUE TITLE
Pass non-CSS props as normal props

### ISSUE THREAD

**Issue by ryanflorence** [smyte/jsxstyle#32]
Since no styles start with `on`, seems like the API could pass along any props that start with `on` as normal event handlers, instead of the hacky `props={}`.

``` js
<Block onScroll={handleScroll}/>
// instead of
<Block props={{ onScroll: handleScroll }}/>
```

This would make wrapping these elements more flexible, like when you need to `cloneElement(children)`

**Comment by petehunt** [comment]
I'm like 85% sold on this. If we do it, we should probably introduce jsxstyle-ified `Input`, `Img` etc tags too.

**Comment by petehunt** [comment]
The way I've currently thought about it is jsxstyle is for style components only, and you need to explicitly introduce separate components for interaction and event handling. It "feels" like a good idea similar to how templates felt like a good idea, but in practice it's annoying.

I think I just convinced myself 100% that we should do this :)

**Comment by petehunt** [comment]
What if instead of passing any prop prefixed with `on`, we just passed any prop that isn't in a whitelist of style props?

**Comment by jaredpalmer** [comment]
@petehunt if we merge #29 , we'd have to also whitelist all pseudo-selector combinations. It's what I wanted to do with #30 initially. Just wasn't sure if a whitelist solution would be performant.

**Comment by threepointone** [comment]
Been using a variant of the whitelist (I also include pseudo selectors etc) for my jsxstyle-ripoff, and it's been nice, no real perf hit https://twitter.com/threepointone/status/763286296802447364

**Comment by hnordt** [comment]
Any updates on this? Would be very nice to be able to style all tags with jsxstyle.

**Comment by meyer** [comment]
@hnordt there’s a PR open that we’re in the process of reviewing (#49).

In the mean time you can already style any tag with jsxstyle by specifying the `component` prop.

```jsx
<Block component="input" props={{type: 'password'}} />
```

**Comment by meyer** [comment]
After some IRL discussion with @ryanflorence I’m going to close this issue. The small number of non-style props on jsxstyle elements does not justify whitelisting every prop passed to every jsxstyle component IMO.
