### ISSUE TITLE
Occasionally getting an error when building example app.

### ISSUE THREAD

**Issue by bryzaguy** [smyte/jsxstyle#40]
I occasionally get the following error when building the sample app:

<img width="607" alt="screen shot 2016-09-29 at 10 20 25 pm" src="https://cloud.githubusercontent.com/assets/2603435/18981730/be80595e-8695-11e6-8dd3-000138fd8663.png">

**Comment by meyer** [comment]
@bryzaguy hmm, that’s funky. I’ll take a look.

**Comment by meyer** [comment]
@bryzaguy I’ve cleaned up example a bit and building has been running smoothly for me. I’m going to close this issue, but please feel free to reopen it if you see it pop up again.
