### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by MofeLee** [smyte/jsxstyle#44]
version: 1.0.1
Android 5.1.1

![image](https://cloud.githubusercontent.com/assets/5069410/19965417/d9e24cca-a201-11e6-88fb-1264db6cb547.png)

![image](https://cloud.githubusercontent.com/assets/5069410/19965519/55ad558e-a202-11e6-8964-611cd91459fe.png)

**Comment by MofeLee** [comment]
version 0.0.22 works fine

**Comment by meyer** [comment]
@MofeLee hmm, this doesn’t look related to jsxstyle. If you see that error again, can you open the stack trace next to the error and post a screenshot here?

**Comment by meyer** [comment]
@MofeLee I’m going to close this as it doesn’t look related to jsxstyle. If you see this error again, can you reopen this issue? It would be extra helpful if you could open the stack trace next to the error as well. Thanks!
