### ISSUE TITLE
Declare event handlers directly on layout elements 

### ISSUE THREAD

**Issue by StokeMasterJack** [smyte/jsxstyle#45]
It would be nice to do this:
`<Block  onClick={this.onRowClick}>Click Me</Block>`

instead of this:
`<Block  props={{onClick: this.onRowClick }}>Click Me</Block>`

**Comment by danielberndt** [comment]
I guess this is a duplicate of https://github.com/smyte/jsxstyle/issues/32?

**Comment by meyer** [comment]
@danielberndt yep!
