### ISSUE TITLE
Compatibility with react-dom@15.4.0

### ISSUE THREAD

**Issue by appsforartists** [smyte/jsxstyle#50]
```
{ Cannot find module 'react/lib/CSSPropertyOperations'
    at $root/node_modules/jsxstyle/lib/createCSS.js:3:29 code: 'MODULE_NOT_FOUND' }
```

**Comment by meyer** [comment]
@appsforartists this change will break React 0.14 compatibility. Will chat with @petehunt IRL about what we should do.

**Comment by Andreyco** [comment]
@appsforartists Superb, thanks for PR. Hope it gets merged soon!

**Comment by tehfailsafe** [comment]
Yes please. Just updated and can't build.

**Comment by meyer** [comment]
@appsforartists thanks for the PR! We decided to extract `CSSPropertyOperations` to its own module.

@Andreyco @tehfailsafe this should be fixed with the next release.

**Comment by Andreyco** [comment]
@meyer Thank you!
