### ISSUE TITLE
will-change for inline styles

### ISSUE THREAD

**Issue by appsforartists** [smyte/jsxstyle#53]
If you animate the value of a jsxstyle (e.g. change `<Block transform = { someChangingValue } />`), you end up with a new style node for every value of `someChangingValue`.  I haven't done extensive performance testing, but my intuition says generating a new style sheet on every frame can't be good for performance; it's less work to set a single style than to instantiate some DOM, inject it into `document.head`, set the class, and let the browser find and update all the affected nodes.  It's also less memory intensive, especially if the developer forgets to call `value.toFixed` and ends up with thousands of generated style nodes that will likely never be recycled.

Have you considered using `willChange` as a sentinel for animations?  Perhaps `willChange` should take an array; any property name in that array will be set as an inline style rather than as a style sheet.

I hope I'm not prematurely optimizing; I know these assumptions should be backed up by data.  Still, curious what your perspective is.

**Comment by meyer** [comment]
@appsforartists this is an issue we’ve run into a few times as well. Creating a new stylesheet on every frame definitely isn’t great. The not-ideal workaround right now is to just use a plain div.

Ideally, style props that change frequently would either be included as actual inline style attributes or would have a special classname and corresponding style tag in `head`. I don’t have a specific opinion on how that should look, but would definitely welcome a PR if you have a solution you were considering.

Unused style tags will be reaped every ten seconds, so the recycle issue shouldn’t be a problem.

**Comment by danielberndt** [comment]
I might out myself as a glamor fanboy here by referring to their solutions once again, but its jsxstyle api would solve it like this:

```
<Flex width="100px" style={{opacity: value}}/>
```

i.e. glamor supports the "old-school" `style` attribute which will be applied as normal inline style onto the dom element. Quite a nice and straight-forward approach to me at least :)

**Comment by appsforartists** [comment]
The thing I like about willChange is you should be setting it anyway if you're animating a property.  If jsxstyle parsed it, you'd be doing the right thing for free.

**Comment by meyer** [comment]
@danielberndt ah yeah, we’ve discussed that option. I’m a fan. I think the only issue is that it moves style props to second level (prop of a prop) but it doesn’t bother me too much, especially given how infrequently it’ll be used.

**Comment by appsforartists** [comment]
@meyer Yup.  They [already do](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change).  This proposal reuses those same semantics to glean out which properties should be inlined.

I like this API because authors should already be `willChange`ing any properties that animate, to allow the browser to render them efficiently.  By teaching `jsxstyle` about this property, you allow it to similarly optimize for animations with no extra work from authors.  If authors are following best practices for animation -- that is, setting `willChange` for any animatable properties -- jsxstyle will do the right thing for free.

**Comment by meyer** [comment]
@appsforartists ohhhhh, the `will-change` *CSS property*. Hmmmmmmmmmmmmmmm. `will-change` and animated jsxstyle props are definitely closely related. My only fear with adding this extra functionality to the `will-change` CSS prop is that we’d be forcing people to opt-in to `will-change` CSS to get somewhat related benefits in JS, and `will-change` is a funky CSS property that needs to be understood completely before it’s used.

I’m not crazy about making one particular CSS prop slightly magical. My general feeling is that, for simplicity’s sake, we should keep `will-change` and jsxstyle performance fixes separate.

**Comment by appsforartists** [comment]
It's only undoing the magic that `jsxstyle` does by default. 😉 

There are three potential states:

a. You want local styles but not `will-change`.
b. You want local styles and `will-change`.
c. You want `will-change`, but not local styles.

This PR solves b.  c seems rare (_maybe_ if you're using the CSS `transition` API?).  It doesn't address a; there may be a separate solution for that.

However, if you're dynamically changing the value of `willChange` (e.g. in `pointerdown`), you'll end up modifying the global stylesheet in that frame.  😕

**Comment by danielberndt** [comment]
I just remember [this 1.5 year old article](http://www.cssmojo.com/the-dark-side-of-the-will-change-property/) claiming that `will-change` leads to inconsistencies depending on whether a browser supports it or not. Do you have any idea whether this is still valid? IE and Edge still [don't seem to support will-change`](http://caniuse.com/#feat=will-change).

While I agree that users should be taught about the benefits of `will-change`, I also agree with @meyer that jsxstyle should attempt to stay as low-level and magic-less as possible. And ideally it won't be very hard to create a custom wrapper around a solution that supports your use case.

**Comment by meyer** [comment]
Alrighty, I’ve thought about this some more. For the time being I’m restoring React’s default `style` prop behaviour. Commit is here: 670d1e181e30754d59462fc5f836dfa359cac67c.

I don’t think using the `style` prop to fix animation performance problems is a good long-term solution though. What I like about the `will-change` proposal is that it’s perfectly explicit, and the user can offload animation performance concerns to jsxstyle.

I’m going to close this issue for now, but I do think this is something we should discuss more in the very near future.
