### ISSUE TITLE
pass trough non css properties

### ISSUE THREAD

**Issue by smeijer** [smyte/jsxstyle#55]
I think non-css properties, like a `onClick` shouldn't be added to the style, but should be passed trough to be handled correctly.

When now declaring a component like:
```js
<Block onClick={() => handleChange(tab)}>{tab}</Block>
```

You end up with:

![image](https://cloud.githubusercontent.com/assets/1196524/20597759/37b191c4-b24e-11e6-9eeb-077fb004d9f0.png)

I think it sucks to have a whitelist due to maintainability (what if the standard releases a new css property name?), but at the same time I think we cannot get around this.

**Comment by meyer** [comment]
@smeijer yep, attribute passthrough is being discussed in #32 and there’s a PR open and under consideration at #49. For now, you can pass any non-style props to the `props` prop (it’s a little meta, I know):

```jsx
<Block props={{onClick: () => console.log('clicked!') }}>Click me!</Block>
```

**Comment by artnez** [comment]
@smeijer If you're down with using the PR now, can add the following to your `package.json`:

```
"dependencies": {
  ...
  "jsxstyle": "https://github.com/artnez/jsxstyle/archive/attribute-passthrough-d.tar.gz",
  ...
}
```

Obviously no guarantees that it'll be merged as-is but everything should work out of the box without extra configuration (it's also backwards compatible with the `props=` attribute).

Passing through attributes using a CSS property whitelist is likely going to happen either way so all you'll need to do is switch NPM dependency versions in the future.
