### ISSUE TITLE
Broken with react@15.4.1

### ISSUE THREAD

**Issue by arturmuller** [smyte/jsxstyle#56]
Hey there. I was just about to test jsxstyle, but missing `CSSPropertyOperations` breaks the build. I see that you've already fixed this in the repo, but it doesn't seem to be on npm, so consider this a gentle nudge. :)

Thanks for an exciting looking library!

**Comment by meyer** [comment]
@arturmuller yep, this was discussed in #50. we’ll be pushing a new build soon.

**Comment by arturmuller** [comment]
Great, thanks!
