### ISSUE TITLE
question: how to get source paths in style inspector

### ISSUE THREAD

**Issue by rchanou** [smyte/jsxstyle#58]
I saw an image showing this feature on Reddit, but it doesn't look like jsxstyle does this out of the box. How do I activate this?

![Style Source Example](https://pbs.twimg.com/media/CDRnDP4UMAEL2U2.png:large)

https://www.reddit.com/r/reactjs/comments/344e0o/what_do_you_you_guys_think_of_petehuntjsxstyle_is/cqrcqrq/

**Comment by meyer** [comment]
@rchanou that’s a feature of the webpack loader, but the loader hasn’t been touched in some time and needs to be updated to work with webpack 2.
