### ISSUE TITLE
React 15.5 deprecation warnings

### ISSUE THREAD

**Issue by rperce** [smyte/jsxstyle#61]
Using `jsxstyle` with versions of React after v15.5.0 produce the following warning: 

```
Warning: Block: React.createClass is deprecated and will be removed in 
version 16. Use plain JavaScript classes instead. If you're not yet ready 
to migrate, create-react-class is available on npm as a drop-in replacement.
``` 

Either `src/makeStyleComponentClass.js` needs to be rewritten or `jsxstyle` needs to add `create-react-class` as a dependency.

**Comment by meyer** [comment]
@rperce yep, we’re on it 😊

**Comment by rperce** [comment]
@meyer awesome! Good to hear :) Let me know if you need extra testing or anything - absolutely love jsxstyle!

**Comment by leoasis** [comment]
@meyer is this being worked on? If not, would you accept a PR that fixes this?

**Comment by meyer** [comment]
@leoasis yep, we’ve migrated `makeStyleComponentClass.js` to ES6 classes. Will have the fix out in the next release.

**Comment by leoasis** [comment]
Awesome, thanks for the response

**Comment by phyrog** [comment]
Any info on when the next release will be (since there hasn't been a commit on `master` since December)?

**Comment by meyer** [comment]
@phyrog I’m aiming to have a new release out in the next week or two. Will have 2.0 WIP up on a branch as soon as we get a chance to discuss things on our end.

**Comment by phyrog** [comment]
@meyer Alright, thanks for the update!

**Comment by hnordt** [comment]
@meyer for now it would be great to at least release a patch to resolve the annoying warnings 🙈
