### ISSUE TITLE
Jest snapshot serializer

### ISSUE THREAD

**Issue by jaredpalmer** [smyte/jsxstyle#64]
If you're using jest snapshots with jsxstyle, this is the current output:

```js
// Jest Snapshot v1, https://goo.gl/fbAQLP


exports[`<Page /> renders Page correctly 1`] = `
<div
      className=" jsxstyle1"
      style={undefined}
    >
      <h1
         className=" jsxstyle2"
         style={undefined}
      >
        Users
      </h1>
</div>
`
```

Would be helpful to get something like [jest-styled-components](https://github.com/styled-components/jest-styled-components) or [jest-glamor-react](https://github.com/kentcdodds/jest-glamor-react) for jsxstyle.

Output would ideally look like: 
```
.jsxstyle0 {
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
}

<h1
  class="jsxstyle0"
>
  Hello World
</h1>
```

We would need to write our own matcher and serializer, but then you could use it like so:
```js
// src/setupTests.js
import {matcher, serializer} from 'jest-jsxstyle'

expect.addSnapshotSerializer(serializer)
expect.extend(matcher)
````

```js
// Something.test.js

import React from 'react'
import renderer from 'react-test-renderer'

test('react-test-renderer', () => {
  const tree = renderer
    .create(
        <Title>Hello World, this is my first jsxstyle component!</Title>,
    )
    .toJSON()

  expect(tree).toMatchSnapshotWithJsxstyle()
})
```

Any thoughts? Would this help people out?

**Comment by meyer** [comment]
@jaredpalmer this would be rad. What would be necessary from the jsxstyle side of things? A hook right where styles are added to document head?

I’ve got a v2 development branch I’m hoping to get pushed up to Github in the next few days. A lot of things have shifted around, but the branch is in a good place. I think adding the necessary bits for better rendering will be pretty straightforward.

**Comment by jaredpalmer** [comment]
@meyer awesome. will get going once you push.

**Comment by jaredpalmer** [comment]
@meyer what's the status of your v2 branch?

**Comment by meyer** [comment]
@jaredpalmer I just pushed the latest code to master a few minutes ago. Shout if you have any questions.

**Comment by jaredpalmer** [comment]
@meyer sweet. looking through now.

**Comment by meyer** [comment]
@jaredpalmer the injectable `addRule` function might be of interest to you:

https://github.com/smyte/jsxstyle/blob/7a10d07c909d870a929a7e5dca32a84accab3deb/src/styleCache.js#L26-L29

I added it for use with server rendering but it’s there to intercept the adding of styles to the document.

**Comment by jaredpalmer** [comment]
@meyer What's the plan for SSR?

**Comment by meyer** [comment]
@jaredpalmer no formal plan, but there are a few things in place for SSR:
- generated class names now use a content hash instead of an incrementing ID, so the same set of CSS props and values are guaranteed to get the same class name.
- the `insertRule` stuff I mentioned above.

Super rough example of `insertAddRule` in use:

```jsx
const fs = require('fs');
const ReactDOMServer = require('react-dom/server');
const { injectAddRule } = require('jsxstyle/lib/styleCache');

const App = require('./path/to/app');

let styles = '';
injectAddRule(rule => styles += rule + '\n');

const body = ReactDOMServer.renderToString(App);
fs.writeFile(
  'build/index.html',
  '<style>' + styles + '</style>' + body
);
```

If you’ve got SSR ideas or opinions I’m all ears! If it’s issue-worthy it might be good to start a new one focussed on the topic.

**Comment by jaredpalmer** [comment]
@meyer have a prototype here: https://github.com/jaredpalmer/jest-jsxstyle 

Got jest working.

Still trying to get enzyme's `mount` and `render` to work (not that pressing though).

Also, I'm not sure I fully understand how/if I should be clearing out the style cache between prints.

**Comment by meyer** [comment]
@jaredpalmer ooh neeeeat. I’m on vacation at the moment but I’ll take a look in a bit.

`resetCache` should be called in between every render (before, to be safe). If a CSS string is present in the cache object, [`insertRule` will not be called][commit]. I considered putting the cache object check in the `insertRule` method instead, but I figured it’s basic deduplication behaviour that anyone who overrides `insertRule` will end up implementing.

[commit]: https://github.com/smyte/jsxstyle/blob/7a10d07/src/styleCache.js#L38

**Comment by sgwilym** [comment]
@jaredpalmer @meyer Thanks for putting together this serialiser, it adds some much needed context to our snapshots! [I've opened a PR](https://github.com/jaredpalmer/jest-jsxstyle/pull/1) for resetting the cache in jest-jsxstyle - is [this](https://github.com/jaredpalmer/jest-jsxstyle/pull/1/files#diff-4568d5ad520ddb6de4962d49a9de1047R19) the right place to do so?

**Comment by meyer** [comment]
I’m going to close this since `jest-jsxstyle` is chugging along quite nicely. Thanks, @jaredpalmer (and @sgwilym for dealing with my API updates)!!

When I get a sec I’ll add `jest-jsxstyle` tests over here as well to make sure things stay in sync.

**Comment by meyer** [comment]
And yay, I just noticed you added pretty printing @sgwilym. I added that for `jest-jsxstyle` but forgot to open a PR over there. Thanks! 🎉
