### ISSUE TITLE
Expand on motivation / justification for jsxstyle

### ISSUE THREAD

**Issue by charlie-axsy** [smyte/jsxstyle#68]
Regarding the section in the FAQ which states that:

> jsxstyle is predicated on the idea that stylesheet rules are not a great way to reuse styles and that components are the correct abstraction.

Since believing in this opinion is vital to developers deciding whether to use this library, please can you expand the readme with more evidence on why you believe that components are the right abstraction.

**Comment by meyer** [comment]
@charlie-axsy very good point. The README is horrendously out of date, but I’m working on a rewrite at the moment. I’ll be sure to explain this more clearly.

**Comment by meyer** [comment]
@charlie-axsy I’m working on the README at the moment. Is there anything in particular about the component model that doesn’t make sense to you? What are you comparing it to?

**Comment by meyer** [comment]
@charlie-axsy README has been completely rewritten. Feel free to reopen this issue if there’s something it doesn’t cover that you think it should.

https://github.com/smyte/jsxstyle/blob/21e5127/packages/jsxstyle/README.md
