### ISSUE TITLE
Convert fractional widths between 0 and 1 to percentages

### ISSUE THREAD

**Issue by meyer** [smyte/jsxstyle#72]
I’m a big fan of [rebass](https://github.com/jxnblk/rebass)’s fractional width feature.

```jsx
// wired
<Block width={3 / 5} />

// tired
<Block width={3 / 5 * 100 + '%'} />
```

Pros:
- Component code is a lot easier to read.
- It’s easier to integrate constants.

Cons:
- it’s slightly magical.

**Comment by petehunt** [comment]
That seems like a good idea.
