### ISSUE TITLE
placeholder rule can cause error in specific browser

### ISSUE THREAD

**Issue by L42y** [smyte/jsxstyle#75]
<img width="923" alt="screen shot 2017-08-24 at 12 52 18 pm" src="https://user-images.githubusercontent.com/284820/29650157-a175c5f8-885e-11e7-92b1-078962b2abed.png">

error is caught in android webview which have user agent: `Mozilla/5.0 (Linux; Android 5.1; m3 note Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.2214.127 Mobile Safari/537.36`, guess it's chrome for android 40?

**Comment by meyer** [comment]
@L42y oh weird. good catch, thanks, I’ll take a look. I suspect it’s happening because `insertRule` has very strict validation and Chrome for Android 40 most likely only supports the `::-webkit-input-placeholder` pseudoelement.

**Comment by meyer** [comment]
@L42y I’ve wrapped `insertRule` in a try/catch block for now. Unfortunately there’s not much else I can do since we’ve decided to move away from autoprefixing at runtime.

**Comment by L42y** [comment]
@meyer thanks, that's enough for now, since I'm using jsxstyle-loader to generate CSS for production environment.

**Comment by meyer** [comment]
@L42y right on, glad you’re finding it useful. Let me know if you run into any funky edge cases.

**Comment by meyer** [comment]
@L42y thanks again for the report. As it turns out this was an issue in quite a few browsers:

https://travis-ci.org/smyte/jsxstyle/builds/275171074#L562
