### ISSUE TITLE
Can we reduce the # of components?

### ISSUE THREAD

**Issue by petehunt** [smyte/jsxstyle#9]
I think we can get away with just `Inline`, `FlexRow`, and `FlexCol`

**Comment by necolas** [comment]
Why `FlexRow` and `FlowCol` rather than just `Flex`?

**Comment by nelix** [comment]
I'm not sure reducing the number of components is useful, perhaps a focus on allowing code to be more expressive? Perhaps @petehunt could grab some metrics on common Component/prop combinations to aid in thinking up some more expressive names for the most common concepts?

**Comment by meyer** [comment]
Proposal:

||Current|Future|
|---|---|---|
|`Inline`|✅️|✅️|
|`Block`|✅️|✅️|
|`InlineBlock`|✅️|✅️|
|`Row`|✅️|✅️|
|`InlineRow`||✅️|
|`Col`|✅️|✅️|
|`InlineCol`||✅️|
|`Flex`|✅️||
|`InlineFlex`|✅️||
|`Table`|✅️||
|`TableRow`|✅️||
|`TableCell`|✅️||

Most used components for me are `Block`, `Row`, then `Col`.

With `Table` and friends, I’m on the fence. I’m not sure there’s a benefit to using `div`s with display set to a table prop. Probably makes more sense to use actual `table`/`tr`/etc. by specifying `component="tr"` on one of the other components.

**Comment by meyer** [comment]
Additional thoughts:
* `Box` might be a good generic name for a containing element.
* inline-ness could be a boolean prop: `<Box inline />`, `<Row inline />`, etc. Only problem is `InlineBlock`. flexbox has mostly removed my need for `display: inline-block` though.
* I like the idea of making primitive layout components a little bit abstract but not too mysterious.

**Comment by hnordt** [comment]
Why remove Flex? and InlineFlex?

**Comment by meyer** [comment]
@hnordt `flex-direction`’s initial value is `row`. `Flex` and `Row` are essentially the same component. `Row` is a bit more explicit than `Flex`, which is a good thing IMO. `InlineFlex` becomes `InlineRow`.

**Comment by hnordt** [comment]
Sounds good @meyer

**Comment by meyer** [comment]
Hmm. In the case where `flex-direction` needs to be set programmatically, overriding the prop on a `Row` component would be a bit strange.

**Comment by meyer** [comment]
I’m still thinking about this, but will close this issue for now.
