### ISSUE TITLE
Module not found: Error: Can't resolve 'jsxstyle/Row'

### ISSUE THREAD

**Issue by StokeMasterJack** [smyte/jsxstyle#94]
After upgrading to 2.06 (from 1.02) I am now getting tons of these errors:

Module not found: Error: Can't resolve 'jsxstyle/Block' 
Module not found: Error: Can't resolve 'jsxstyle/Row'
Module not found: Error: Can't resolve 'jsxstyle/Col'

My imports look like this:
import Block from "jsxstyle/Block"

**Comment by meyer** [comment]
@StokeMasterJack ah yep. With jsxstyle 1, components were defined in one file and then aliased to `jsxstyle/Row`, `jsxstyle/Col`, etc. For jsxstyle 2, those aliases were removed in favour of destructuring. If you transpile your JS, you can require jsxstyle components like so:

```js
const { Block, Row, Col } = require('jsxstyle');
```

Destructured syntax is the recommended way to import jsxstyle components, but you can also manually destructure:

```js
const Block = require('jsxstyle').Block;
const Row = require('jsxstyle').Row;
const Col = require('jsxstyle').Col;
```

**Comment by StokeMasterJack** [comment]
OK. Thanks. I ended up doing that. It was a pretty big git commit. Touched 100s of files.

**Comment by meyer** [comment]
@StokeMasterJack yeah, we should’ve encourage destructured syntax from the beginning. Sorry about that.
